### ISSUE TITLE
Images 404 Not Found in website

### ISSUE THREAD

**Issue by andhie** [Groovman/motocal#4]
The website https://motocal-groovman.netlify.com/ unable to load any images

![screenshot 2019-02-06 at 3 50 24 pm](https://user-images.githubusercontent.com/3997169/52327437-1707f780-2a27-11e9-852a-efc07adebdef.jpg)

**Comment by Groovman** [comment]
It is not able to load images because there are none, the site is only to deploy nightly builds so people can calculate stuff that was just released before the changes are merged into the stable version git.
